behaviors:
  Gerald:
    trainer_type: ppo
    max_steps: 5000
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 1.0e-2
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      hidden_units: 128
      sequence_length: 64
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    curiosity:
      strength: 0.0
    default:
      max_step: 5000
